import { CellType as C } from '@piximps/domain/types'
import { Template } from '@piximps/domain/template'
import { type TemplateRegistry } from './types'

const _ = C.AlwaysEmpty
const P = C.Probabilistic
const F = C.AlwaysFilled
const B = C.InnerBody

const stocky8 = new Template({
  grid: [
    [_, _, F, F],
    [_, F, B, B],
    [_, F, B, B],
    [F, F, B, B],
    [F, F, B, B],
    [P, F, F, F],
    [_, F, _, F],
    [_, F, _, F],
  ],
  anchors: {
    horns: { row: 0, columnStart: 2, columnEnd: 3 },
    eyes: { row: 2, columnStart: 1, columnEnd: 3 },
    mouth: { row: 3, columnStart: 2, columnEnd: 3 },
  },
  compatibleWith: ['wide-horns', 'small-horns', 'single-eye', 'double-eye', 'fangs', 'grin'],
  symmetric: true,
})

const lanky8 = new Template({
  grid: [
    [_, _, F, F],
    [_, _, B, B],
    [_, F, B, B],
    [_, F, B, F],
    [_, F, B, F],
    [_, F, F, P],
    [_, _, F, _],
    [_, _, F, _],
  ],
  anchors: {
    horns: { row: 0, columnStart: 2, columnEnd: 3 },
    eyes: { row: 1, columnStart: 2, columnEnd: 3 },
    mouth: { row: 2, columnStart: 2, columnEnd: 3 },
  },
  compatibleWith: ['tall-horns', 'small-horns', 'single-eye', 'double-eye', 'fangs', 'smirk'],
  symmetric: true,
})

const round8 = new Template({
  grid: [
    [_, _, F, F],
    [_, F, B, B],
    [F, B, B, B],
    [F, B, B, B],
    [F, B, B, B],
    [_, F, B, B],
    [_, _, F, F],
    [_, _, P, F],
  ],
  anchors: {
    horns: { row: 0, columnStart: 2, columnEnd: 3 },
    eyes: { row: 2, columnStart: 1, columnEnd: 3 },
    mouth: { row: 4, columnStart: 1, columnEnd: 3 },
  },
  compatibleWith: ['wide-horns', 'small-horns', 'triple-eye', 'double-eye', 'fangs', 'grin'],
  symmetric: true,
})

const stocky16 = new Template({
  grid: [
    [_, _, _, _, _, _, _, _],
    [_, _, _, _, _, _, _, _],
    [_, _, _, _, _, _, _, _],
    [_, _, _, _, F, F, F, P],
    [_, _, _, F, F, B, B, B],
    [_, _, _, F, B, B, B, B],
    [_, _, _, F, B, B, B, B],
    [_, _, _, F, F, B, F, F],
    [_, _, _, _, F, B, F, _],
    [_, _, P, F, F, B, B, F],
    [_, _, F, F, B, B, B, F],
    [_, _, F, F, B, B, B, F],
    [_, _, _, F, F, B, F, F],
    [_, _, _, _, F, F, F, _],
    [_, _, _, _, F, _, F, _],
    [_, _, _, P, F, _, F, _],
  ],
  anchors: {
    horns: { row: 3, columnStart: 4, columnEnd: 7 },
    eyes: { row: 5, columnStart: 3, columnEnd: 7 },
    mouth: { row: 7, columnStart: 4, columnEnd: 7 },
  },
  compatibleWith: ['wide-horns', 'small-horns', 'single-eye', 'double-eye', 'fangs', 'grin'],
  symmetric: true,
})

const lanky16 = new Template({
  grid: [
    [_, _, _, _, _, _, _, _],
    [_, _, _, _, _, _, _, _],
    [_, _, _, _, _, F, F, F],
    [_, _, _, _, F, B, B, B],
    [_, _, _, _, F, B, B, B],
    [_, _, _, _, F, B, B, B],
    [_, _, _, _, _, F, F, F],
    [_, _, _, _, _, F, B, F],
    [_, _, _, _, F, F, B, F],
    [_, _, _, _, F, B, B, F],
    [_, _, _, _, F, B, B, F],
    [_, _, _, _, F, B, B, P],
    [_, _, _, _, F, F, F, _],
    [_, _, _, _, _, F, _, _],
    [_, _, _, _, _, F, _, _],
    [_, _, _, _, _, F, _, _],
  ],
  anchors: {
    horns: { row: 2, columnStart: 5, columnEnd: 7 },
    eyes: { row: 4, columnStart: 4, columnEnd: 7 },
    mouth: { row: 5, columnStart: 5, columnEnd: 7 },
  },
  compatibleWith: ['tall-horns', 'small-horns', 'single-eye', 'double-eye', 'fangs', 'smirk'],
  symmetric: true,
})

const round16 = new Template({
  grid: [
    [_, _, _, _, _, _, _, _],
    [_, _, _, _, _, _, _, _],
    [_, _, _, _, _, F, F, F],
    [_, _, _, _, F, B, B, B],
    [_, _, _, F, B, B, B, B],
    [_, _, _, F, B, B, B, B],
    [_, _, F, F, B, B, B, B],
    [_, _, F, B, B, B, B, B],
    [_, F, F, B, B, B, B, B],
    [_, F, B, B, B, B, B, B],
    [_, F, F, B, B, B, B, B],
    [_, _, F, F, B, B, B, B],
    [_, _, _, F, F, B, B, F],
    [_, _, _, _, F, F, F, _],
    [_, _, _, _, _, F, F, _],
    [_, _, _, _, P, F, F, _],
  ],
  anchors: {
    horns: { row: 2, columnStart: 5, columnEnd: 7 },
    eyes: { row: 4, columnStart: 3, columnEnd: 7 },
    mouth: { row: 6, columnStart: 3, columnEnd: 7 },
  },
  compatibleWith: ['wide-horns', 'small-horns', 'triple-eye', 'double-eye', 'fangs', 'grin'],
  symmetric: true,
})

const hunched16 = new Template({
  grid: [
    [_, _, _, _, _, _, _, _],
    [_, _, _, _, _, _, _, _],
    [_, _, _, _, _, _, _, _],
    [_, _, _, _, _, F, F, P],
    [_, _, _, _, F, B, B, B],
    [_, _, _, _, F, B, B, B],
    [_, _, _, _, F, B, F, F],
    [_, _, _, F, F, B, F, _],
    [_, _, F, F, B, B, B, F],
    [_, P, F, B, B, B, B, F],
    [_, _, F, F, B, B, B, F],
    [_, _, F, F, B, B, B, F],
    [_, _, _, F, F, B, B, F],
    [_, _, _, F, F, F, F, _],
    [_, _, _, F, _, _, F, _],
    [_, _, _, F, _, _, F, _],
  ],
  anchors: {
    horns: { row: 3, columnStart: 5, columnEnd: 7 },
    eyes: { row: 5, columnStart: 4, columnEnd: 7 },
    mouth: { row: 6, columnStart: 5, columnEnd: 7 },
  },
  compatibleWith: ['wide-horns', 'tall-horns', 'single-eye', 'double-eye', 'fangs', 'smirk'],
  symmetric: true,
})

const stocky32 = new Template({
  grid: [
    [_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _],
    [_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _],
    [_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _],
    [_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _],
    [_, _, _, _, _, _, _, _, _, _, _, F, F, F, F, P],
    [_, _, _, _, _, _, _, _, _, _, F, F, B, B, B, B],
    [_, _, _, _, _, _, _, _, _, _, F, B, B, B, B, B],
    [_, _, _, _, _, _, _, _, _, _, F, B, B, B, B, B],
    [_, _, _, _, _, _, _, _, _, _, F, B, B, B, B, B],
    [_, _, _, _, _, _, _, _, _, _, F, B, B, B, B, B],
    [_, _, _, _, _, _, _, _, _, _, F, F, B, B, F, F],
    [_, _, _, _, _, _, _, _, _, _, _, F, B, B, F, _],
    [_, _, _, _, _, _, _, _, _, _, _, F, F, B, F, _],
    [_, _, _, _, _, _, _, _, _, _, F, F, B, B, F, _],
    [_, _, _, _, _, _, _, _, P, F, F, B, B, B, B, F],
    [_, _, _, _, _, _, _, _, F, F, B, B, B, B, B, F],
    [_, _, _, _, _, _, _, _, F, F, B, B, B, B, B, F],
    [_, _, _, _, _, _, _, _, F, F, B, B, B, B, B, F],
    [_, _, _, _, _, _, _, _, P, F, B, B, B, B, B, F],
    [_, _, _, _, _, _, _, _, _, F, F, B, B, B, B, F],
    [_, _, _, _, _, _, _, _, _, F, F, B, B, B, B, F],
    [_, _, _, _, _, _, _, _, _, _, F, F, B, B, B, F],
    [_, _, _, _, _, _, _, _, _, _, _, F, F, B, B, F],
    [_, _, _, _, _, _, _, _, _, _, _, F, F, B, F, F],
    [_, _, _, _, _, _, _, _, _, _, _, _, F, F, F, _],
    [_, _, _, _, _, _, _, _, _, _, _, _, F, F, F, _],
    [_, _, _, _, _, _, _, _, _, _, _, _, F, _, F, _],
    [_, _, _, _, _, _, _, _, _, _, _, _, F, _, F, _],
    [_, _, _, _, _, _, _, _, _, _, _, _, F, _, F, _],
    [_, _, _, _, _, _, _, _, _, _, _, P, F, _, F, _],
    [_, _, _, _, _, _, _, _, _, _, _, F, F, _, F, F],
    [_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _],
  ],
  anchors: {
    horns: { row: 4, columnStart: 11, columnEnd: 15 },
    eyes: { row: 7, columnStart: 10, columnEnd: 15 },
    mouth: { row: 10, columnStart: 11, columnEnd: 15 },
  },
  compatibleWith: ['wide-horns', 'small-horns', 'single-eye', 'double-eye', 'fangs', 'grin'],
  symmetric: true,
})

const lanky32 = new Template({
  grid: [
    [_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _],
    [_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _],
    [_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _],
    [_, _, _, _, _, _, _, _, _, _, _, _, F, F, F, F],
    [_, _, _, _, _, _, _, _, _, _, _, F, B, B, B, B],
    [_, _, _, _, _, _, _, _, _, _, _, F, B, B, B, B],
    [_, _, _, _, _, _, _, _, _, _, _, F, B, B, B, B],
    [_, _, _, _, _, _, _, _, _, _, _, F, B, B, B, B],
    [_, _, _, _, _, _, _, _, _, _, _, _, F, F, F, F],
    [_, _, _, _, _, _, _, _, _, _, _, _, F, B, B, F],
    [_, _, _, _, _, _, _, _, _, _, _, _, F, B, B, F],
    [_, _, _, _, _, _, _, _, _, _, _, F, F, B, B, F],
    [_, _, _, _, _, _, _, _, _, _, _, F, B, B, B, F],
    [_, _, _, _, _, _, _, _, _, _, _, F, B, B, B, F],
    [_, _, _, _, _, _, _, _, _, _, _, F, B, B, B, F],
    [_, _, _, _, _, _, _, _, _, _, _, F, B, B, B, F],
    [_, _, _, _, _, _, _, _, _, _, _, F, B, B, B, P],
    [_, _, _, _, _, _, _, _, _, _, _, F, B, B, B, F],
    [_, _, _, _, _, _, _, _, _, _, _, F, B, B, B, F],
    [_, _, _, _, _, _, _, _, _, _, _, F, F, B, B, F],
    [_, _, _, _, _, _, _, _, _, _, _, _, F, F, B, F],
    [_, _, _, _, _, _, _, _, _, _, _, _, F, F, F, _],
    [_, _, _, _, _, _, _, _, _, _, _, _, _, F, _, _],
    [_, _, _, _, _, _, _, _, _, _, _, _, _, F, _, _],
    [_, _, _, _, _, _, _, _, _, _, _, _, _, F, _, _],
    [_, _, _, _, _, _, _, _, _, _, _, _, _, F, _, _],
    [_, _, _, _, _, _, _, _, _, _, _, _, _, F, _, _],
    [_, _, _, _, _, _, _, _, _, _, _, _, _, F, _, _],
    [_, _, _, _, _, _, _, _, _, _, _, _, _, F, _, _],
    [_, _, _, _, _, _, _, _, _, _, _, _, _, F, _, _],
    [_, _, _, _, _, _, _, _, _, _, _, _, _, F, F, _],
    [_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _],
  ],
  anchors: {
    horns: { row: 3, columnStart: 12, columnEnd: 15 },
    eyes: { row: 5, columnStart: 11, columnEnd: 15 },
    mouth: { row: 7, columnStart: 12, columnEnd: 15 },
  },
  compatibleWith: ['tall-horns', 'small-horns', 'single-eye', 'double-eye', 'fangs', 'smirk'],
  symmetric: true,
})

const round32 = new Template({
  grid: [
    [_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _],
    [_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _],
    [_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _],
    [_, _, _, _, _, _, _, _, _, _, _, _, F, F, F, P],
    [_, _, _, _, _, _, _, _, _, _, _, F, B, B, B, B],
    [_, _, _, _, _, _, _, _, _, _, F, B, B, B, B, B],
    [_, _, _, _, _, _, _, _, _, F, B, B, B, B, B, B],
    [_, _, _, _, _, _, _, _, F, F, B, B, B, B, B, B],
    [_, _, _, _, _, _, _, F, F, B, B, B, B, B, B, B],
    [_, _, _, _, _, _, F, F, B, B, B, B, B, B, B, B],
    [_, _, _, _, _, _, F, B, B, B, B, B, B, B, B, B],
    [_, _, _, _, _, F, F, B, B, B, B, B, B, B, B, B],
    [_, _, _, _, _, F, B, B, B, B, B, B, B, B, B, B],
    [_, _, _, _, _, F, F, B, B, B, B, B, B, B, B, B],
    [_, _, _, _, _, _, F, B, B, B, B, B, B, B, B, B],
    [_, _, _, _, _, _, F, F, B, B, B, B, B, B, B, B],
    [_, _, _, _, _, _, _, F, F, B, B, B, B, B, B, B],
    [_, _, _, _, _, _, _, _, F, F, B, B, B, B, B, B],
    [_, _, _, _, _, _, _, _, _, F, F, B, B, B, B, B],
    [_, _, _, _, _, _, _, _, _, _, F, F, B, B, B, B],
    [_, _, _, _, _, _, _, _, _, _, _, F, F, B, B, F],
    [_, _, _, _, _, _, _, _, _, _, _, _, F, F, F, _],
    [_, _, _, _, _, _, _, _, _, _, _, _, _, F, F, _],
    [_, _, _, _, _, _, _, _, _, _, _, _, _, F, F, _],
    [_, _, _, _, _, _, _, _, _, _, _, _, _, F, _, _],
    [_, _, _, _, _, _, _, _, _, _, _, _, _, F, _, _],
    [_, _, _, _, _, _, _, _, _, _, _, _, P, F, _, _],
    [_, _, _, _, _, _, _, _, _, _, _, _, F, F, _, _],
    [_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _],
    [_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _],
    [_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _],
    [_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _],
  ],
  anchors: {
    horns: { row: 3, columnStart: 12, columnEnd: 15 },
    eyes: { row: 6, columnStart: 9, columnEnd: 15 },
    mouth: { row: 10, columnStart: 7, columnEnd: 15 },
  },
  compatibleWith: ['wide-horns', 'small-horns', 'triple-eye', 'double-eye', 'fangs', 'grin'],
  symmetric: true,
})

const hunched32 = new Template({
  grid: [
    [_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _],
    [_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _],
    [_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _],
    [_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _],
    [_, _, _, _, _, _, _, _, _, _, _, _, F, F, F, P],
    [_, _, _, _, _, _, _, _, _, _, _, F, B, B, B, B],
    [_, _, _, _, _, _, _, _, _, _, _, F, B, B, B, B],
    [_, _, _, _, _, _, _, _, _, _, _, F, B, B, B, B],
    [_, _, _, _, _, _, _, _, _, _, _, F, B, B, F, F],
    [_, _, _, _, _, _, _, _, _, _, _, _, F, B, F, _],
    [_, _, _, _, _, _, _, _, _, _, F, F, F, B, F, _],
    [_, _, _, _, _, _, _, _, _, F, F, B, B, B, F, _],
    [_, _, _, _, _, _, _, _, F, F, B, B, B, B, B, F],
    [_, _, _, _, _, _, _, P, F, B, B, B, B, B, B, F],
    [_, _, _, _, _, _, _, _, F, F, B, B, B, B, B, F],
    [_, _, _, _, _, _, _, _, F, F, B, B, B, B, B, F],
    [_, _, _, _, _, _, _, _, _, F, F, B, B, B, B, F],
    [_, _, _, _, _, _, _, _, _, F, F, B, B, B, B, F],
    [_, _, _, _, _, _, _, _, _, _, F, F, B, B, B, F],
    [_, _, _, _, _, _, _, _, _, _, F, F, B, B, B, F],
    [_, _, _, _, _, _, _, _, _, _, _, F, F, B, B, F],
    [_, _, _, _, _, _, _, _, _, _, _, F, F, F, F, _],
    [_, _, _, _, _, _, _, _, _, _, _, F, _, _, F, _],
    [_, _, _, _, _, _, _, _, _, _, _, F, _, _, F, _],
    [_, _, _, _, _, _, _, _, _, _, _, F, _, _, F, _],
    [_, _, _, _, _, _, _, _, _, _, _, F, _, _, F, _],
    [_, _, _, _, _, _, _, _, _, _, _, F, _, _, F, _],
    [_, _, _, _, _, _, _, _, _, _, _, F, _, _, F, _],
    [_, _, _, _, _, _, _, _, _, _, _, F, F, _, F, F],
    [_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _],
    [_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _],
    [_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _],
  ],
  anchors: {
    horns: { row: 4, columnStart: 12, columnEnd: 15 },
    eyes: { row: 6, columnStart: 11, columnEnd: 15 },
    mouth: { row: 8, columnStart: 12, columnEnd: 15 },
  },
  compatibleWith: ['wide-horns', 'tall-horns', 'single-eye', 'double-eye', 'fangs', 'smirk'],
  symmetric: true,
})

export const bodyTemplates: TemplateRegistry = {
  8: [stocky8, lanky8, round8],
  16: [stocky16, lanky16, round16, hunched16],
  32: [stocky32, lanky32, round32, hunched32],
}
